export const ROUTES = Object.freeze({
	APP_ENTRY_SCREEN: 'APP_ENTRY_SCREEN_EXAMPLES_APP',
	FITNESS_ENTRY: 'FITNESS_ENTRY',
	FITNESS_ENTRY_SCREEN: 'FITNESS_ENTRY_SCREEN',
	MOBILE_FLASHCARD_ENTRY: 'MOBILE_FLASHCARD_ENTRY',
	MOBILE_FLASHCARD_ENTRY_SCREEN: 'MOBILE_FLASHCARD_ENTRY_SCREEN',

	/**
	 * @routes {MF}
	 * This is all the routes for {MOBILE_FLASHCARD_ENTRY SCREENS}
	 */
	MF_DECK_LIST: 'MOBILE_FLASHCARD_DECK_LIST_SCREEN',
	MF_NEW_DECK: 'MOBILE_FLASHCARD_NEW_DECK_SCREEN',
	MF_QUIZ_HOME: 'MOBILE_FLASHCARD_QUIZ_HOME_SCREEN',
	MF_ADD_CARD: 'MOBILE_FLASHCARD_ADD_SCREEN',
	MF_SCORE: 'MOBILE_FLASHCARD_SCORE_SCREEN',
	MF_SINGLE_DECK: 'MOBILE_FLASHCARD_SINGLE_DECK_SCREEN',

	/**
	 * @routes {FI}
	 * This is all the routes for {FITNESS_ENTRY SCREENS}
	 */
});
