export const ROUTES = Object.freeze({
	APP_ENTRY_SCREEN: 'APP_ENTRY_SCREEN_EXAMPLES_APP',
	FITNESS_ENTRY: 'FITNESS_ENTRY',
	FITNESS_ENTRY_SCREEN: 'FITNESS_ENTRY_SCREEN',
	MOBILE_FLASHCARD_ENTRY: 'MOBILE_FLASHCARD_ENTRY',
	MOBILE_FLASHCARD_ENTRY_SCREEN: 'MOBILE_FLASHCARD_ENTRY_SCREEN',
});
